/**
 * The MSW worker for browser-mode tests. It registers a Service Worker
 * (`public/mockServiceWorker.js`, generated by `msw init`) that intercepts every
 * fetch the page makes — including the cross-origin call to the oRPC endpoint.
 * Lifecycle (start / reset / stop) is driven from `../setup.ts`.
 */
import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
