/**
 * MSW request handlers for the oRPC API.
 *
 * Rather than hand-craft oRPC's wire envelope, we mount a real server-side
 * `RPCHandler` — built by `implement`-ing the shared contract — and let it speak
 * the protocol. MSW intercepts the browser's fetch to the RPC endpoint and hands
 * the request to that handler, so serialisation and routing match production
 * exactly.
 *
 * `auth.me`, `entries.list`, and `entries.create` are mocked. Add procedures
 * here as the new surface — and the tests that exercise it — take shape.
 */
import { implement } from "@orpc/server";
import { RPCHandler } from "@orpc/server/fetch";
import { http, passthrough } from "msw";
import { contract, toEntrySummary } from "@rhymelab/api-contract";
import { fakeEntries } from "@rhymelab/fixtures";

/** Base URL the oRPC client targets (see `src/lib/orpc.ts`). */
export const RPC_URL = "http://localhost:4000/rpc";

/** No accounts yet — the mock, like the API, scopes every row to one user. */
const MOCK_USER_ID = "mock-user";

/**
 * Fixture entries the mocked `entries.list` returns — generated by the shared
 * `@rhymelab/fixtures` package (same generator the API stub uses, so the mock and
 * the real endpoint can't drift). The seed is fixed and distinct from the API's,
 * so this set is stable and the Library test can assert against `store.entries`.
 */
const ENTRIES = fakeEntries(5, { seed: 424242 });

/** Backing state the mocked procedures read from. */
export const store = {
  /** What `auth.me` reports — flip to exercise the redirect guard. */
  authed: true,
  /** What `entries.list` returns. */
  entries: ENTRIES,
};

/** Wipe the store back to defaults. Called from `afterEach` in the setup file. */
export function resetStore(): void {
  store.authed = true;
  store.entries = ENTRIES;
}

const os = implement(contract);

const router = {
  auth: {
    me: os.auth.me.handler(() => ({ authed: store.authed })),
  },
  entries: {
    list: os.entries.list.handler(() =>
      [...store.entries].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)),
    ),
    create: os.entries.create.handler(({ input }) => {
      const now = new Date();
      // Build the row the API would store, then map it with the very same
      // `toEntrySummary` the real handler uses — so the optional fields collapse
      // to "" and the summary fields derive from `body` exactly as in production,
      // rather than by a lookalike written out here.
      const entry = toEntrySummary({
        id: crypto.randomUUID(),
        userId: MOCK_USER_ID,
        kind: input.kind,
        title: input.title,
        author: input.author ?? null,
        year: input.year ?? null,
        body: input.body,
        artist: input.kind === "lyrics" ? (input.artist ?? null) : null,
        album: input.kind === "lyrics" ? (input.album ?? null) : null,
        createdAt: now,
        updatedAt: now,
      });
      store.entries = [entry, ...store.entries];
      return entry;
    }),
  },
};

const rpcHandler = new RPCHandler(router);

export const handlers = [
  http.all(`${RPC_URL}/*`, async ({ request }) => {
    // MSW's `StrictRequest` is a real Fetch `Request` at runtime; the cast only
    // sheds the Cloudflare `cf` property this package's global `Request` carries.
    const { matched, response } = await rpcHandler.handle(request as unknown as Request, {
      prefix: "/rpc",
    });
    if (matched) return response;
    return passthrough();
  }),
];
