/**
 * MSW request handlers for the oRPC API.
 *
 * Rather than hand-craft oRPC's wire envelope, we mount a real server-side
 * `RPCHandler` — built by `implement`-ing the shared contract — and let it speak
 * the protocol. MSW intercepts the browser's fetch to the RPC endpoint and hands
 * the request to that handler, so serialisation and routing match production
 * exactly.
 *
 * `auth.me`, `entries.list`, `entries.create`, `entries.get`, and
 * `entries.delete` are mocked. Add procedures here as the new surface — and the
 * tests that exercise it — take shape.
 */
import { implement, ORPCError } from "@orpc/server";
import { RPCHandler } from "@orpc/server/fetch";
import { http, passthrough } from "msw";
import { contract, deriveEntrySummaryFields } from "@rhymelab/api-contract";
import { fakeEntries } from "@rhymelab/fixtures";

/** Base URL the oRPC client targets (see `src/lib/orpc.ts`). */
export const RPC_URL = "http://localhost:4000/rpc";

/**
 * Fixture entries the mocked `entries.list` returns — generated by the shared
 * `@rhymelab/fixtures` package (same generator the API stub uses, so the mock and
 * the real endpoint can't drift). The seed is fixed and distinct from the API's,
 * so this set is stable and the Library test can assert against `store.entries`.
 */
const ENTRIES = fakeEntries(5, { seed: 424242 });

/** Backing state the mocked procedures read from. */
export const store = {
  /** What `auth.me` reports — flip to exercise the redirect guard. */
  authed: true,
  /** What `entries.list` returns. */
  entries: ENTRIES,
};

/** Wipe the store back to defaults. Called from `afterEach` in the setup file. */
export function resetStore(): void {
  store.authed = true;
  store.entries = ENTRIES;
}

const os = implement(contract);

const router = {
  auth: {
    me: os.auth.me.handler(() => ({ authed: store.authed })),
  },
  entries: {
    list: os.entries.list.handler(() =>
      [...store.entries].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)),
    ),
    create: os.entries.create.handler(({ input }) => {
      const now = new Date().toISOString();
      // The optional scalars collapse to "" on the wire shape, matching the real
      // API: it stores them as nullable columns and maps NULL to "" on read. The
      // list fields (`author`/`artist`) are already defaulted to `[]` by the
      // contract, so they pass straight through.
      const base = {
        id: crypto.randomUUID(),
        title: input.title,
        author: input.author,
        year: input.year,
        body: input.body,
        ...deriveEntrySummaryFields(input.body),
        createdAt: now,
        updatedAt: now,
      };
      const entry =
        input.kind === "lyrics"
          ? {
              ...base,
              kind: "lyrics" as const,
              artist: input.artist,
              album: input.album ?? "",
            }
          : { ...base, kind: "poem" as const };
      store.entries = [entry, ...store.entries];
      return entry;
    }),
    get: os.entries.get.handler(({ input }) => {
      const entry = store.entries.find((candidate) => candidate.id === input.id);
      if (!entry) throw new ORPCError("NOT_FOUND");
      // Every entry (fixture-seeded or created above) carries a real `body`; drop
      // the list-view-only derived fields the detail shape doesn't want.
      const { excerpt: _excerpt, lineCount: _lineCount, wordCount: _wordCount, ...detail } = entry;
      return detail;
    }),
    delete: os.entries.delete.handler(({ input }) => {
      const entry = store.entries.find((candidate) => candidate.id === input.id);
      if (!entry) throw new ORPCError("NOT_FOUND");
      // The real delete is soft, but the tombstone is invisible over the wire —
      // a deleted piece is simply gone from every response, so dropping it from
      // the store is a faithful mock of what a client can observe.
      store.entries = store.entries.filter((candidate) => candidate.id !== input.id);
      return { ok: true } as const;
    }),
  },
};

const rpcHandler = new RPCHandler(router);

export const handlers = [
  http.all(`${RPC_URL}/*`, async ({ request }) => {
    // MSW's `StrictRequest` is a real Fetch `Request` at runtime; the cast only
    // sheds the Cloudflare `cf` property this package's global `Request` carries.
    const { matched, response } = await rpcHandler.handle(request as unknown as Request, {
      prefix: "/rpc",
    });
    if (matched) return response;
    return passthrough();
  }),
];
