/**
 * MSW request handlers for the oRPC API.
 *
 * Rather than hand-craft oRPC's wire envelope, we mount a real server-side
 * `RPCHandler` — built by `implement`-ing the shared contract — and let it speak
 * the protocol. MSW intercepts the browser's fetch to the RPC endpoint and hands
 * the request to that handler, so serialisation and routing match production
 * exactly.
 *
 * `auth.me`, `entries.list`, and `entries.create` are mocked. Add procedures
 * here as the new surface — and the tests that exercise it — take shape.
 */
import { implement } from "@orpc/server";
import { RPCHandler } from "@orpc/server/fetch";
import { http, passthrough } from "msw";
import { contract } from "@rhymelab/api-contract";
import { fakeEntries } from "@rhymelab/fixtures";

/** Base URL the oRPC client targets (see `src/lib/orpc.ts`). */
export const RPC_URL = "http://localhost:4000/rpc";

/**
 * Fixture entries the mocked `entries.list` returns — generated by the shared
 * `@rhymelab/fixtures` package (same generator the API stub uses, so the mock and
 * the real endpoint can't drift). The seed is fixed and distinct from the API's,
 * so this set is stable and the Library test can assert against `store.entries`.
 */
const ENTRIES = fakeEntries(5, { seed: 424242 });

/** Backing state the mocked procedures read from. */
export const store = {
  /** What `auth.me` reports — flip to exercise the redirect guard. */
  authed: true,
  /** What `entries.list` returns. */
  entries: ENTRIES,
};

/** Wipe the store back to defaults. Called from `afterEach` in the setup file. */
export function resetStore(): void {
  store.authed = true;
  store.entries = ENTRIES;
}

const os = implement(contract);

/**
 * Derive the list-view fields from `body`, the same way the real API handler
 * does, so a created entry reads back the way the server would return it.
 */
function summarize(body: string) {
  const lines = body.split("\n");
  const excerpt =
    lines
      .map((line) => line.trim())
      .filter(Boolean)
      .slice(0, 2)
      .join(" / ") || body.trim();
  return {
    excerpt,
    lineCount: lines.length,
    wordCount: body.split(/\s+/).filter(Boolean).length,
  };
}

const router = {
  auth: {
    me: os.auth.me.handler(() => ({ authed: store.authed })),
  },
  entries: {
    list: os.entries.list.handler(() =>
      [...store.entries].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)),
    ),
    create: os.entries.create.handler(({ input }) => {
      const now = new Date().toISOString();
      const base = {
        id: crypto.randomUUID(),
        title: input.title,
        author: input.author,
        year: input.year,
        ...summarize(input.body),
        createdAt: now,
        updatedAt: now,
      };
      const entry =
        input.kind === "lyrics"
          ? { ...base, kind: "lyrics" as const, artist: input.artist, album: input.album }
          : { ...base, kind: "poem" as const };
      store.entries = [entry, ...store.entries];
      return entry;
    }),
  },
};

const rpcHandler = new RPCHandler(router);

export const handlers = [
  http.all(`${RPC_URL}/*`, async ({ request }) => {
    // MSW's `StrictRequest` is a real Fetch `Request` at runtime; the cast only
    // sheds the Cloudflare `cf` property this package's global `Request` carries.
    const { matched, response } = await rpcHandler.handle(request as unknown as Request, {
      prefix: "/rpc",
    });
    if (matched) return response;
    return passthrough();
  }),
];
