/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthLogoutIndexRouteImport } from './routes/auth/logout/index'
import { Route as AuthenticatedAccountProfileIndexRouteImport } from './routes/_authenticated/account/profile/index'
import { Route as AuthenticatedAccountSettingsIndexRouteImport } from './routes/_authenticated/account/settings/index'
import { Route as AuthenticatedEntriesEntryIdIndexRouteImport } from './routes/_authenticated/entries/$entryId/index'
import { Route as AuthenticatedEntriesNewIndexRouteImport } from './routes/_authenticated/entries/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutIndexRoute = AuthLogoutIndexRouteImport.update({
  id: '/auth/logout/',
  path: '/auth/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountProfileIndexRoute =
  AuthenticatedAccountProfileIndexRouteImport.update({
    id: '/account/profile/',
    path: '/account/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsIndexRoute =
  AuthenticatedAccountSettingsIndexRouteImport.update({
    id: '/account/settings/',
    path: '/account/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntriesEntryIdIndexRoute =
  AuthenticatedEntriesEntryIdIndexRouteImport.update({
    id: '/entries/$entryId/',
    path: '/entries/$entryId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntriesNewIndexRoute =
  AuthenticatedEntriesNewIndexRouteImport.update({
    id: '/entries/new/',
    path: '/entries/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/account/profile/': typeof AuthenticatedAccountProfileIndexRoute
  '/account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/entries/$entryId/': typeof AuthenticatedEntriesEntryIdIndexRoute
  '/entries/new/': typeof AuthenticatedEntriesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/logout': typeof AuthLogoutIndexRoute
  '/account/profile': typeof AuthenticatedAccountProfileIndexRoute
  '/account/settings': typeof AuthenticatedAccountSettingsIndexRoute
  '/entries/$entryId': typeof AuthenticatedEntriesEntryIdIndexRoute
  '/entries/new': typeof AuthenticatedEntriesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/_authenticated/account/profile/': typeof AuthenticatedAccountProfileIndexRoute
  '/_authenticated/account/settings/': typeof AuthenticatedAccountSettingsIndexRoute
  '/_authenticated/entries/$entryId/': typeof AuthenticatedEntriesEntryIdIndexRoute
  '/_authenticated/entries/new/': typeof AuthenticatedEntriesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/'
    | '/library/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/account/profile/'
    | '/account/settings/'
    | '/entries/$entryId/'
    | '/entries/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/library'
    | '/auth/login'
    | '/auth/logout'
    | '/account/profile'
    | '/account/settings'
    | '/entries/$entryId'
    | '/entries/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home/'
    | '/_authenticated/library/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/_authenticated/account/profile/'
    | '/_authenticated/account/settings/'
    | '/_authenticated/entries/$entryId/'
    | '/_authenticated/entries/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLogoutIndexRoute: typeof AuthLogoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout/': {
      id: '/auth/logout/'
      path: '/auth/logout'
      fullPath: '/auth/logout/'
      preLoaderRoute: typeof AuthLogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/profile/': {
      id: '/_authenticated/account/profile/'
      path: '/account/profile'
      fullPath: '/account/profile/'
      preLoaderRoute: typeof AuthenticatedAccountProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/settings/': {
      id: '/_authenticated/account/settings/'
      path: '/account/settings'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AuthenticatedAccountSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entries/$entryId/': {
      id: '/_authenticated/entries/$entryId/'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId/'
      preLoaderRoute: typeof AuthenticatedEntriesEntryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entries/new/': {
      id: '/_authenticated/entries/new/'
      path: '/entries/new'
      fullPath: '/entries/new/'
      preLoaderRoute: typeof AuthenticatedEntriesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedAccountProfileIndexRoute: typeof AuthenticatedAccountProfileIndexRoute
  AuthenticatedAccountSettingsIndexRoute: typeof AuthenticatedAccountSettingsIndexRoute
  AuthenticatedEntriesEntryIdIndexRoute: typeof AuthenticatedEntriesEntryIdIndexRoute
  AuthenticatedEntriesNewIndexRoute: typeof AuthenticatedEntriesNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedAccountProfileIndexRoute: AuthenticatedAccountProfileIndexRoute,
  AuthenticatedAccountSettingsIndexRoute:
    AuthenticatedAccountSettingsIndexRoute,
  AuthenticatedEntriesEntryIdIndexRoute: AuthenticatedEntriesEntryIdIndexRoute,
  AuthenticatedEntriesNewIndexRoute: AuthenticatedEntriesNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLogoutIndexRoute: AuthLogoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
