/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthLogoutIndexRouteImport } from './routes/auth/logout/index'
import { Route as AuthenticatedEntriesEntryIdIndexRouteImport } from './routes/_authenticated/entries/$entryId/index'
import { Route as AuthenticatedEntriesNewIndexRouteImport } from './routes/_authenticated/entries/new/index'
import { Route as AuthenticatedEntriesEntryIdEditIndexRouteImport } from './routes/_authenticated/entries/$entryId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutIndexRoute = AuthLogoutIndexRouteImport.update({
  id: '/auth/logout/',
  path: '/auth/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEntriesEntryIdIndexRoute =
  AuthenticatedEntriesEntryIdIndexRouteImport.update({
    id: '/entries/$entryId/',
    path: '/entries/$entryId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntriesNewIndexRoute =
  AuthenticatedEntriesNewIndexRouteImport.update({
    id: '/entries/new/',
    path: '/entries/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntriesEntryIdEditIndexRoute =
  AuthenticatedEntriesEntryIdEditIndexRouteImport.update({
    id: '/entries/$entryId/edit/',
    path: '/entries/$entryId/edit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/entries/$entryId/': typeof AuthenticatedEntriesEntryIdIndexRoute
  '/entries/new/': typeof AuthenticatedEntriesNewIndexRoute
  '/entries/$entryId/edit/': typeof AuthenticatedEntriesEntryIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/logout': typeof AuthLogoutIndexRoute
  '/entries/$entryId': typeof AuthenticatedEntriesEntryIdIndexRoute
  '/entries/new': typeof AuthenticatedEntriesNewIndexRoute
  '/entries/$entryId/edit': typeof AuthenticatedEntriesEntryIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/_authenticated/entries/$entryId/': typeof AuthenticatedEntriesEntryIdIndexRoute
  '/_authenticated/entries/new/': typeof AuthenticatedEntriesNewIndexRoute
  '/_authenticated/entries/$entryId/edit/': typeof AuthenticatedEntriesEntryIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/entries/$entryId/'
    | '/entries/new/'
    | '/entries/$entryId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/auth/login'
    | '/auth/logout'
    | '/entries/$entryId'
    | '/entries/new'
    | '/entries/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/library/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/_authenticated/entries/$entryId/'
    | '/_authenticated/entries/new/'
    | '/_authenticated/entries/$entryId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLogoutIndexRoute: typeof AuthLogoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout/': {
      id: '/auth/logout/'
      path: '/auth/logout'
      fullPath: '/auth/logout/'
      preLoaderRoute: typeof AuthLogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entries/$entryId/': {
      id: '/_authenticated/entries/$entryId/'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId/'
      preLoaderRoute: typeof AuthenticatedEntriesEntryIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entries/new/': {
      id: '/_authenticated/entries/new/'
      path: '/entries/new'
      fullPath: '/entries/new/'
      preLoaderRoute: typeof AuthenticatedEntriesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entries/$entryId/edit/': {
      id: '/_authenticated/entries/$entryId/edit/'
      path: '/entries/$entryId/edit'
      fullPath: '/entries/$entryId/edit/'
      preLoaderRoute: typeof AuthenticatedEntriesEntryIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedEntriesEntryIdIndexRoute: typeof AuthenticatedEntriesEntryIdIndexRoute
  AuthenticatedEntriesNewIndexRoute: typeof AuthenticatedEntriesNewIndexRoute
  AuthenticatedEntriesEntryIdEditIndexRoute: typeof AuthenticatedEntriesEntryIdEditIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedEntriesEntryIdIndexRoute: AuthenticatedEntriesEntryIdIndexRoute,
  AuthenticatedEntriesNewIndexRoute: AuthenticatedEntriesNewIndexRoute,
  AuthenticatedEntriesEntryIdEditIndexRoute:
    AuthenticatedEntriesEntryIdEditIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLogoutIndexRoute: AuthLogoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
